# gz topic published by the simulator core
- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# gz topic published by IMU plugin
- ros_topic_name: "imu"
  gz_topic_name: "imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Lidar)
- ros_topic_name: "scan"
  gz_topic_name: "scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# gz topic published by the Pose publisher plugin
- ros_topic_name: "sitoe_robot/pose"
  gz_topic_name: "sitoe_robot/pose"
  ros_type_name: "geometry_msgs/msg/Pose"
  gz_type_name: "gz.msgs.Pose"
  direction: GZ_TO_ROS

# # gz topic published by Sensors plugin (Base Bumper Contact)
- ros_topic_name: "base_collisions"
  gz_topic_name: "base_collisions"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS

# # gz topic published by Sensors plugin (Left Wheel Bumper Contact)
- ros_topic_name: "left_wheel_collisions"
  gz_topic_name: "left_wheel_collisions"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Right Wheel Bumper Contact)
- ros_topic_name: "right_wheel_collisions"
  gz_topic_name: "right_wheel_collisions"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Top Camera Color)
- ros_topic_name: "top_camera_color/camera_info"
  gz_topic_name: "top_camera_color/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Bottom Camera Color)
- ros_topic_name: "bottom_camera_color/camera_info"
  gz_topic_name: "bottom_camera_color/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Top Camera Depth)
- ros_topic_name: "top_camera_depth/camera_info"
  gz_topic_name: "top_camera_depth/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Bottom Camera Depth)
- ros_topic_name: "bottom_camera_depth/camera_info"
  gz_topic_name: "bottom_camera_depth/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# gz topic published for Sensors plugin (Top depth camera point cloud)
- ros_topic_name: "top_camera_depth/points"
  gz_topic_name: "top_camera_depth/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

# gz topic published for Sensors plugin (Bottom depth camera point cloud)
- ros_topic_name: "bottom_camera_depth/points"
  gz_topic_name: "bottom_camera_depth/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

 # gz topic published by DiffDrive plugin
- ros_topic_name: "odom"
  gz_topic_name: "odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# gz topic published by DiffDrive plugin
- ros_topic_name: "tf"
  gz_topic_name: "tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# gz topic subscribed to by DiffDrive plugin
- ros_topic_name: "robot_base_controller/cmd_vel_unstamped"
  gz_topic_name: "cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# gz topic published by JointState plugin
- ros_topic_name: "joint_states"
  gz_topic_name: "joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
